// GENERATED by scripts/gen-parity-cases.ts — do not edit by hand.
// (replay id, feature vector, expected total from TS scorer, expected recommendation)
pub const CASES: &[(&str, [u64; 8], u64, u64)] = &[
    ("gmx_oracle_manipulation_2022", [1, 2410000, 1870000, 0, 4, 0, 0, 1], 63, 2),
    ("camelot_flash_drain_2023", [1, 1520000, 1480000, 0, 3, 0, 0, 0], 30, 0),
    ("radiant_flashloan_2024", [1, 1150000, 980000, 0, 4, 0, 1, 1], 73, 2),
];
