// Generates contracts-stylus/tests/parity_cases.rs from the off-chain
// TypeScript scorer so the Rust unit tests assert against the exact values
// the TS engine produces for the three historical replays.
//
// Run: pnpm gen:parity
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { scoreThreat } from "../skill/detection/engine.js";
import { extractFeatures, scoreFeatures } from "../skill/detection/features.js";
import { getReplayIds, getReplayInput } from "../skill/detection/replays/index.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const lines: string[] = [
  "// GENERATED by scripts/gen-parity-cases.ts — do not edit by hand.",
  "// (replay id, feature vector, expected total from TS scorer, expected recommendation)",
  "pub const CASES: &[(&str, [u64; 8], u64, u64)] = &[",
];

for (const id of getReplayIds()) {
  const input = getReplayInput(id)!;
  const tsScore = scoreThreat(input).score;
  const features = extractFeatures(input);
  const intScore = scoreFeatures(features);
  if (intScore.total !== tsScore) {
    throw new Error(
      `Integer scorer diverges from TS float scorer on ${id}: ${intScore.total} != ${tsScore}`
    );
  }
  lines.push(
    `    ("${id}", [${features.join(", ")}], ${tsScore}, ${intScore.recommendation}),`
  );
  console.log(
    `${id}: features=[${features.join(",")}] ts_score=${tsScore} recommendation=${intScore.recommendation}`
  );
}
lines.push("];", "");

const out = join(root, "contracts-stylus", "tests", "parity_cases.rs");
writeFileSync(out, lines.join("\n"));
console.log(`wrote ${out}`);
